// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class BookingSlot
{
    public int BookingId { get; set; }

    public int Vstid { get; set; }

    public DateOnly? BookDate { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual VenueServiceTime Vst { get; set; }
}