// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public int? UserId { get; set; }

    public int? CourtId { get; set; }

    public int? NumberOfGuest { get; set; }

    public string SpecialNote { get; set; }

    public int? TotalPrice { get; set; }

    public string Status { get; set; }

    public string BookingItemsNames => string.Join(", ", BookingItems.Select(bi => bi.Item.Name));
    public string BookingSlotsDates => string.Join(", ", BookingSlots.Select(bs => bs.BookDate));
    public string BookingSlotsTimes => string.Join(", ", BookingSlots.Select(bs => bs.Vst.TimeSlot.Value));

    public virtual ICollection<BookingItem> BookingItems { get; set; } = new List<BookingItem>();

    public virtual ICollection<BookingSlot> BookingSlots { get; set; } = new List<BookingSlot>();

    public virtual BadmintonCourt Court { get; set; }

    public virtual User User { get; set; }
}