// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class BookingItem
{
    public int BookingId { get; set; }

    public int ItemId { get; set; }

    public int? UnitQuantity { get; set; }

    public int? SumPrice { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Item Item { get; set; }
}