// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class ItemType
{
    public int ItemTypeId { get; set; }

    public string Type { get; set; }

    public virtual ICollection<Item> Items { get; set; } = new List<Item>();
}