// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Item
{
    public int ItemId { get; set; }

    public int? ItemTypeId { get; set; }

    public string Name { get; set; }

    public int? Price { get; set; }

    public virtual ICollection<BookingItem> BookingItems { get; set; } = new List<BookingItem>();

    public virtual ItemType ItemType { get; set; }
}