// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class TimeSlot
{
    public int TimeSlotId { get; set; }

    public string Name { get; set; }

    public string Value { get; set; }

    public virtual ICollection<VenueServiceTime> VenueServiceTimes { get; set; } = new List<VenueServiceTime>();
}