// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class VenueServiceTime
{
    public int Vstid { get; set; }

    public int? TimeSlotId { get; set; }

    public int? CourtId { get; set; }

    public virtual ICollection<BookingSlot> BookingSlots { get; set; } = new List<BookingSlot>();

    public virtual BadmintonCourt Court { get; set; }

    public virtual TimeSlot TimeSlot { get; set; }
}